name: Node Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm ci
        npm run build

    # deploy to server
    - name: Copy artifacts to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_ADDRESS }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        port: 22
        source: "dist/spa/*"
        target: ${{ secrets.SERVER_PATH }}
        overwrite: 1
        strip_components: 1
